spring: 
  application:
    name: mmb-eureka-server

server:
  port: 8011
  
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/

#spring: 
#  application:
#    name: eureka-server-clustered
#  profiles: primary
#server:
#  port: 8011
#eureka:
#  instance:
#    hostname: eureka-primary
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/
#---
#spring:
#  application:
#    name: eureka-server-clustered
#  profiles: secondary
#server:
#  port: 8012
#eureka:
#  instance:
#    hostname: eureka-secondary
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://eureka-primary:8011/eureka/,http://eureka-tertiary:8013/eureka/
#---
#spring:
#  application:
#    name: eureka-server-clustered
#  profiles: tertiary
#server:
#  port: 8013
#eureka:
#  instance:
#    hostname: eureka-tertiary
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://eureka-primary:8011/eureka/,http://eureka-secondary:8012/eureka/